name: jenkins-maven-cd
description: Deploys a Maven project to the Jenkins Artifactory repository in continuous delivery style.
inputs:
  GITHUB_TOKEN:
    required: true
    description: Token to run with, defaults to the repository GITHUB_TOKEN
  MAVEN_USERNAME:
    required: true
    description: Maven username used for deploying the plugin jar to Jenkins Artifactory Repository
  MAVEN_TOKEN:
    required: true
    description: Maven token used for deploying the plugin jar to Jenkins Artifactory Repository
  INTERESTING_CATEGORIES:
    required: true
    description: |
      Regexp of emojis from https://github.com/jenkinsci/.github/blob/master/.github/release-drafter.yml representing changes of interest to users.
      By default excludes 📦📝👻🚦 under the assumption these do not normally merit a release.
      Ignored when using workflow_dispatch (explicit release); when using the check_run trigger (automatic), the release is skipped unless the draft changelog matches.
    default: '[💥🚨🎉🐛⚠🚀🌐👷]|:(boom|tada|construction_worker):'
runs:
  using: composite
  steps:
    - run: $GITHUB_ACTION_PATH/run.sh
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        MAVEN_USERNAME: ${{ inputs.MAVEN_USERNAME }}
        MAVEN_TOKEN: ${{ inputs.MAVEN_TOKEN }}
        INTERESTING_CATEGORIES: ${{ inputs.INTERESTING_CATEGORIES }}
